require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp_config")
require("core.plugin_config.nvim-autopairs_config")
require("core.plugin_config.which-key_config")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.oil_config")
require("core.plugin_config.catppuccin")
require("core.plugin_config.code-completion")
require("core.plugin_config.toggleterm")
require("core.plugin_config.hop_config")
require("core.plugin_config.illuminate")
require("core.plugin_config.symbols-outline")

